# Build stage
FROM golang:1.21-alpine3.18 AS builder
WORKDIR /app
RUN go install github.com/cosmtrek/air@latest
COPY . .
RUN go build -o main main.go

# Run stage
FROM alpine:3.18
WORKDIR /app
COPY --from=builder /app/main .
COPY app.env .
COPY start.sh .
COPY wait-for.sh .
COPY db/migration ./db/migration

EXPOSE 8080
CMD [ "air", "-c", ".air.toml" ]
